### ISSUE TITLE
TNT Breaks Bedrock

### ISSUE THREAD

**Issue by HYPExMon5ter** [Serilum/.issue-tracker#106]
Mod doesn't seem to work with either biomes o plenty or forgeendertech and/or nether portal fix. Upon trying to blow up bedrock this shows in console https://pastebin.com/EQjpdQSG

**Comment by ricksouth** [comment]
I've installed all the mods combined with TNT Breaks Bedrock and everything works correctly. I also don't see any errors relating to my mod in your log. I'm pretty sure your problem lies somewhere else. Thanks for using the mod!

![2020-05-10_17 14 57](https://user-images.githubusercontent.com/38502394/81503060-e1b12000-92e1-11ea-95fc-cb72c3b8d0f0.png)
![2020-05-10_17 15 08](https://user-images.githubusercontent.com/38502394/81503063-e249b680-92e1-11ea-8c6c-b4d770f617d9.png)
