### ISSUE TITLE
[1.15.2-crash dedicated server[mod villagernames]

### ISSUE THREAD

**Issue by SDUBZ** [Serilum/.issue-tracker#118]
## **Information**
Minecraft version 1.15.2
Forge version: 31.1.77
Environment: Multiplayer

Mod name: villager names
Mod version: villagernames_1.15-2.2

## **Description**
was exploring and the server crashed from village name

## **Crash report**
If available.
[crash-2020-05-13_20.11.55-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/4626054/crash-2020-05-13_20.11.55-server.txt)

**Comment by SDUBZ** [comment]
hers the logs from the server : 
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/4626236/latest.log)

[debug.log](https://github.com/ricksouth/serilum-mc-mods/files/4626234/debug.log)

**Comment by ricksouth** [comment]
It seems like Enchanced Animals causes the exception, because they're not using the code a vanilla mob has.

But it should be fixed nonetheless in version 2.3. Thanks for letting me know and sorry for the inconvenience. Again, if it's not working feel free to open another issue. But I'm pretty confident this time!

[https://www.curseforge.com/minecraft/mc-mods/villager-names](https://www.curseforge.com/minecraft/mc-mods/villager-names)
