### ISSUE TITLE
1.12.2

### ISSUE THREAD

**Issue by Lacaxoto** [Serilum/.issue-tracker#124]
## **Information**
Mod name: Enchanting Commands

## **Feature description**
Hi, i'd like to know if you could bring this mod to 1.12.2.

**Comment by MokahTGS** [comment]
Yes please!!

**Comment by ricksouth** [comment]
A 1.12 version is already available! Because it's "old" CurseForge hides the previous versions on the main page. It is however visible under all files:

[https://www.curseforge.com/minecraft/mc-mods/enchanting-commands/files/2786879](https://www.curseforge.com/minecraft/mc-mods/enchanting-commands/files/2786879)

Thanks for the interest!
