### ISSUE TITLE
crash on server[1.15.2-forge] [ justmobheads]

### ISSUE THREAD

**Issue by SDUBZ** [Serilum/.issue-tracker#126]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.2.0
Environment: Multiplayer

Mod name: Mod
Mod version: 2.2 justmobheads

## **Description**
was fight a mob  and then this crashed the server

## **Crash report**
If available.
[crash-2020-05-24_12.28.46-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/4675587/crash-2020-05-24_12.28.46-server.txt)

**Comment by ricksouth** [comment]
This was due to an incompatibility with another mod you had installed. I've fixed it on my end in the latest version, together with some other new features. Thanks for letting me know and using the mod!

[https://www.curseforge.com/minecraft/mc-mods/just-mob-heads](https://www.curseforge.com/minecraft/mc-mods/just-mob-heads)
