### ISSUE TITLE
Add modifiers for different mobs

### ISSUE THREAD

**Issue by SwanX1** [Serilum/.issue-tracker#129]
## **Information**
Mod name: Altered Damage

## **Feature description**
Add it so that different damage types or different mobs can have different damage modifiers.
For example:
I want to make a skeleton deal less damage, but the zombie - more, however all the quark mobs deal no damage.
I'd just type something like
```
{
  "minecraft:skeleton": {
    "damageModifier": 0.5
  },
  "minecraft:zombie": {
    "damageModifier": 2
  },
  "quark:*": {
    "damageModifier": 0
  }
}
```
in the config (doesn't have to be JSON), and it would _obviously_ change the damage individually.
It also might be cool to add environment damage (i.e. fall damage, drowning damage).

**Comment by nmarshall23** [comment]
It might also be interesting to change values by entity type. Zombie, Spider, etc.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
