### ISSUE TITLE
[Suggestion] Add Villager Name support to Farlanders

### ISSUE THREAD

**Issue by Spearkiller** [Serilum/.issue-tracker#149]
## **Information**
Mod name: Villager Names

## **Feature description**
Pretty simple idea really. Add an interaction between this mod and Farlanders, which would allow this mod to name all Farlander villagers (Maybe the golems and such as well? Maybe also have it changeable in the config to name the Ender Golems). Because they're not normal villagers, you could have more fun with a variety of more exotic or just outright nonsensical names.

**Comment by ricksouth** [comment]
Thanks for the suggestion! I've added the Farlander, Elder Farlander, Wanderer and Rebel to be named with villager names. I didn't add the golems, because the vanilla golems also aren't named. Also, if you've got an iron farm it might be a bit more traumatic to see all the named golems melt down into a few iron ingots :disappointed: 

Only Collective needs an update, Villager Names should pick up the change without one.

**Comment by ricksouth** [comment]
![2020-06-17_08 43 38](https://user-images.githubusercontent.com/38502394/84864257-ae974480-b076-11ea-83c9-10d85686db7a.png)

**Comment by PItlosTails** [comment]
oh my god i was about to ask if it was a bug that farlanders are named but it appears not, thanks so much for adding this to the game, it really adds a lot of flavour to the game
