### ISSUE TITLE
Block Tags

### ISSUE THREAD

**Issue by WenXin20** [Serilum/.issue-tracker#151]
## **Information**
Minecraft version: 1.15.2

Mod name: Nether Portal Spread
Mod version: 3.2

## **Question**
Does this mod work with block tags to define what block can change into another?

**Comment by ricksouth** [comment]
On first boot the mod uses the config spread settings in /config/netherportalspread/ and converts those into the block variants by using the resource locations. Does that answer your question?

**Comment by WenXin20** [comment]
No, sorry. I meant can I, for example, use the block tag #minecraft:small_flowers in the config as an input or output for what a block can change into for the Nether Portal spread?

And will this work for the config of Random Bonemeal Flowers as well?

**Comment by ricksouth** [comment]
Ah, no sorry. But you can add all the flower types you'd want to spawn with the same weight. That should have the same effect, just a little more text. 

Random Bone Meal Flowers chooses one at random from the flowers which are not blacklisted. As the name suggests

**Comment by WenXin20** [comment]
Is tag support possible to add for Nether Portal Spread? Then I could input #forge:dirt and #minecraft:stone without having to type out each modded block individually.

**Comment by ricksouth** [comment]
Hmm, that would indeed be a nice thing to have. I don't have much experience with the tags though. I'll try some code! Do you have an example from another mod which uses the tags system within a config file?

**Comment by WenXin20** [comment]
Hmm, none that I can think of at the moment. I believe this is because it is usually done through the datapacks system instead of the configs.

The mod Cyclic has tools called Scythes, which checks for blocks tagged with #cyclic:scythe_forage, which in the file, checks for blocks tagged with #minecraft:small_flowers.

And I'm pretty sure that minecraft bees check for flowers that use the block tag #minecraft:small_flowers.

Hope this helps any. :)

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
