### ISSUE TITLE
Add flowers to the list

### ISSUE THREAD

**Issue by WenXin20** [Serilum/.issue-tracker#158]
## **Information**
Minecraft version: 1.15.2

Mod name: Random Bone Meal Flowers
Mod version: 1.2

## **Question**
Some mod flowers are not automatically added to the blacklist, such as the flowers from the Flower Breeding mod.
 Is it possible to add plants to the blacklist manually, even if they are not normally flowers? Like cattails from Swamp Expansion?

**Comment by ricksouth** [comment]
Both the Flower Breeding mod and Swamp Expansion uses BushBlocks and not FlowerBlocks, which is why they're currently not supported. Do they spawn when you use bone meal on grass?

**Comment by WenXin20** [comment]
No they don't, even if added to the list.

**Comment by ricksouth** [comment]
Yea the list only works with FlowerBlocks. I don't really want to add support for BushBlocks because of the mod name, and because bushes don't spawn with the default bone meal behaviour. I assume there's a reason Flower Breeding extends BushBlocks and not FlowerBlock.

Thanks for the suggestion though!
