### ISSUE TITLE
Collective question...

### ISSUE THREAD

**Issue by parthenon-v** [Serilum/.issue-tracker#161]
Mod name: Collective

## **Question**
Why is there no version of the Collective mod for 1.12.2? I can't seem to get Husk Spawn to work :(

**Comment by ricksouth** [comment]
Hi, thanks for the interest! Unfortunately Collective was made after support for 1.12 was dropped, and because so much code was rewritten in 1.13, I had to make a choice. Updating 90 mods was hard enough with 2 versions, adding another one with a different code base would've made it even more difficult.

I'd suggest you update to 1.14 or 1.15, I'm not the only author who has stopped developing for 1.12.
