### ISSUE TITLE
Some ideas for Enchanting Commands mod.

### ISSUE THREAD

**Issue by uhm0311** [Serilum/.issue-tracker#181]
## **Information**
Mod name: Enchanting Commands

## **Feature description**
1. Add 'all' in enchantment list. If I command /ec enchant all 10, my item will be enchanted with all of enchantment level 10.

2. Add 'natural' in level list. If I command /ec enchant sharpness natural, my item will be enchanted with sharpness level 5. level 5 is the maximum value of sharpness on Enchanting Table.

3. Can command with enchantment code. If I command /ec 34 2, my item will be enchanted with unbreaking level 2.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
