### ISSUE TITLE
SleepSooner doesn't work in Survival.

### ISSUE THREAD

**Issue by subilphilip** [Serilum/.issue-tracker#190]
I have a bunch of Serilum mods installed, which includes SleepSooner and EasyElytraTakeoff (both for 1.16). While using SleepSooner in creative mode, it works just fine, but while in survival mode, it doesn't skip forward the time, but it does show the message. Also EET doesn't work with the CuriousElytra mod, so if they that could be made compatible, it would be very useful.

**Comment by ricksouth** [comment]
I've added support for Curious Elytra in version 1.5 of EET.

As for the Sleep Sooner mod, I've just tested it with the 1.16.2 version and it works as intended. Both in survival and creative. Could you re-test it? Otherwise it might be a problem with another mod. Please open another issue if the problem persists.

Thanks for using the mods!
