### ISSUE TITLE
Add config for setting the default dimension

### ISSUE THREAD

**Issue by kreezxil** [Serilum/.issue-tracker#199]
see also: #97 

For 1.16.1, the other mod for Forge is NetherSpawn but it is broken, I have submitted a bug report for it https://github.com/LotsOfCheese/netherspawn/issues/1

I think it would be better if your mod supported setting any dimension as the default dimension. I would use it for the Nether, but I could see someone an end city as a start zone. Or any number of a dimensions.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
