### ISSUE TITLE
Suggestion-Starter Kit option to use bonus chest loot table

### ISSUE THREAD

**Issue by PurpleHel** [Serilum/.issue-tracker#203]
It'd be neat if there was a config option to make Starter Kit give items according to the bonus chest loot table. This would be really useful on servers, or with mods like Village Spawn Point that interfere with the bonus chest being created.

You make such great mods!

**Comment by James103** [comment]
What if you could use any loot table (including custom loot tables) to populate the player's starting inventory? For example, instead of just defining what they start with in the config file, the config file could hold a pointer to a loot table, which is then used to populate the player's inventory.

Edit: This would also resolve #218, #186, and #179 since they all rely on NBT data, which is currently unsupported but would be supported with the new custom loot table system.

**Comment by ricksouth** [comment]
For now I've added support for NBT tags and a '/starterkit set' command. I'll give the custom loot tables a try in the future. Thanks @PurpleHel and @James103 for the idea :)

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
