### ISSUE TITLE
Make a 1.12.2 version of First Join Message

### ISSUE THREAD

**Issue by ZaneDragonBorn** [Serilum/.issue-tracker#204]
## **Information**
Mod name: First Join Message

## **Feature description**
As most people know 1.12 has the most mods (at least from 1.11 to 1.16) which means most modpacks are on that version. So if someone is hosting a server higher chances it's on 1.12. since there is very little mods on 1.16 that make it worth making a server for them I think this mod would get more known on 1.12. Plus there are no mods like this for that version.

**Comment by ricksouth** [comment]
I understand that you'd like the mod for the version you're currently using, but 1.12 is no longer supported by the Forge team and the code format has changed drastically since 1.13. As of now I have to support 3 active versions (1.14, 1.15 and 1.16) which already takes a lot of time. Adding 1.12 with the other format is too much.

Thanks for the interest though!
