### ISSUE TITLE
Make Set World Spawn Point compatible with other dimensions

### ISSUE THREAD

**Issue by hohserg1** [Serilum/.issue-tracker#229]
## **Information**
Minecraft version: 1.12.2
Forge version: 14.23.5.2854
Environment: Singleplayer

Mod name: Set World Spawn Point
Mod version: 1.1

## **Description**
I did set world spawn point in config to 0 100 0
On first enter to The End plaer spawned at 0 40 0 - incorrectly
On second and next player spawned at 0 100 0 - correctly

## **setworldsp.cfg**
```
# Configuration file

general {
    # If enabled, spawns players on the exact world spawn instead of around it.
    B:_forceExactSpawn=true

    # The X coordinate of the spawn point of newly created worlds.
    # Min: -100000
    # Max: 100000
    I:xCoordSpawnPoint=0

    # The Y coordinate of the spawn point of newly created worlds. By default -1, which means it'll be the first solid block descending from y=256.
    # Min: -1
    # Max: 256
    I:yCoordSpawnPoint=100

    # The Z coordinate of the spawn point of newly created worlds.
    # Min: -100000
    # Max: 100000
    I:zCoordSpawnPoint=0
}


```

**Comment by James103** [comment]
Does the obsidian platform still generate centered on (0, 100, 0) even if the first player entering gets sent to (0, 40, 0), using your configuration?

**Comment by ricksouth** [comment]
At this moment the mod is intended to work with only the overworld. But I'm planning on adding compatibility with the other (modded) dimensions. It's on the to-do list. Thanks for using the mod!

**Comment by hohserg1** [comment]
> Does the obsidian platform still generate centered on (0, 100, 0) even if the first player entering gets sent to (0, 40, 0), using your configuration?

Obsidian plate still generate at regular location, but generation of spawn is not requirement feature.
I need to set spawnpoint in world hardly

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
