### ISSUE TITLE
Idea: Durability and correct tool handling for Better Beacon/Conduit Placement

### ISSUE THREAD

**Issue by James103** [Serilum/.issue-tracker#234]
## **Information**
Mod name: Better Beacon/Conduit Placement

## **Feature description**
Would it be possible to add a config setting to make it so breaking beacon blocks and using beacon blocks to replace other blocks should require the proper tool and consume the correct amount of durability? (Note: The below examples also apply to Conduits if you change some of the numbers around)

Example 1: Player places a beacon base block when there is a stone block in a way.
Current: No durability damage is dealt to any tools and the operation succeeds.
Expected: A pickaxe in your inventory takes durability damage. If you don't have any pickaxes, the operation fails.

Example 2: Player sneaks to place 64 beacon base blocks at once when there is all dirt in the way. The only shovel they have equipped is unenchanted and has 32 durability remaining.
Current: No durability damage is dealt to any tools and the operation fully succeeds.
Expected: The shovel breaks, and only 32 out of the 64 beacon base blocks are placed.

Example 3: Player breaks a beacon block powered by a level 4 pyramid using a diamond pickaxe with 1561 durability.
Current: Diamond pickaxe takes 1 durability damage.
Expected: Diamond pickaxe takes 165 durability damage (1 beacon + 164 base blocks).

Example 4: Player breaks a beacon block powered by a level 4 pyramid using a iron pickaxe with 32 durability. The pyramid contains some netherite blocks in the top levels.
Current: All blocks are broken, iron pickaxe takes 1 durability damage.
Expected: Only 32 of the non-netherite blocks are broken, leaving the netherite blocks in the top level(s) intact.

I understand if this is out of scope or too difficult to implement, but it would make more sense that way.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
