### ISSUE TITLE
Nameable Mobs

### ISSUE THREAD

**Issue by ScoutTheSaneless** [Serilum/.issue-tracker#252]
## **Information**
Mod name: Mob Names

## **Feature description**
I've had this amazing idea..Much like the pets and villager names mod, what if there were names for all the mobs in game? If not all the mobs, maybe the illagers? I would believe that the illagers would have names for each other if not any other mob (at least to our knowledge, dumb language barriers between species...)

**Comment by ricksouth** [comment]
I appreciate the new mod suggestion! I have added your idea to the list. I'm keeping track of all ideas on the Trello page and added the URL of this issue there.

In order to reduce the amount of open issues on this Github repository, I'll be closing this issue.

It definitely does not mean I am not interested and I'll post a comment here if/when the mod is released. This might take some time, as bug reports take priority. But I'll definitely be releasing more mods along the way.

Thank you very much for the suggestion!

**Comment by ScoutTheSaneless** [comment]
That's awesome! Truth be told, I had completely forgotten I left this idea XD! But ye, I agree that ironing out bugs takes more issue than a while new project, so take your time!
