### ISSUE TITLE
Assistance with Mod Incompatibility - Easy Elytra Takeoff 1.12.2

### ISSUE THREAD

**Issue by Jalalien-mc** [Serilum/.issue-tracker#253]
Hello there!  I have a quick question if you'd (possibly) be able to help me out.  I run a small Minecraft server with some lag issues, so your Easy Elytra Takeoff mod is a lifesaver!  We've been running into some issues with server crashes when taking off, however, which has made using it difficult.  The issue isn't with the mod itself, but rather an overlapping feature with another mod.  Unfortunately, I'm not very technically knowledgeable, so that's the most I've been able to glean from the crash reports.  I've attached an example crash report below.  I'd be happy to grab some other ones if that might help.  Do you think you could take a look and see if anything jumps out as an issue?

The two mods we have that seem to provide obvious (potential) conflicts to me are Quark, which allows for dyeing elytra different colors as well as crafting new ones by copying existing ones, and RandomPatches, which both increases the elytra speed limit compared to Vanilla as well as fixing "the player model occasionally disappearing when flying with elytra in a straight line in third-person mode" (quoted from its config file).

The quark features and the model fix can be turned off completely in the config files, whereas the speed limit increase can only be set back to the Vanilla value (300) so I'm unsure if it wouldn't still conflict if that turns out to be the issue.

Any help you could provide would be greatly appreciated!

Here's the standard prompt information and the crash report:
## **Information**
Minecraft version: 1.12.2
Magma version: c40b4af
Environment: Multiplayer

Mod name: Easy Elytra Takeoff
Mod version: 1.12-1.1

[crash-2020-08-29_05.59.39-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/5159027/crash-2020-08-29_05.59.39-server.txt)

**Comment by ricksouth** [comment]
It's unfortunately not something I can make compatible on just my end without redesigning the mod. The error isn't raised from any direct code in the mod, but indirectly from the main code of the game.

Also I don't support version 1.12 anymore, sorry for the inconvenience. Thanks for the interest though!

**Comment by Niko-sk2x** [comment]
This is a bug in this mod, it's not really an incompatibility, and it affects all Minecraft versions. Minecraft doesn't support spawning entities outside of server tick thread [like this](https://github.com/ricksouth/serilum-mc-mods/blob/6832f1f35920c6e078ef46bff803042d2a491d8d/sources/Easy%20Elytra%20Takeoff/src/main/java/com/natamus/easyelytratakeoff/events/ElytraEvent.java#L111-L156). This mod is creating new threads for spawning some entities.

This just happens to work most of the time because it's unlikely that Minecraft will be running entity tracking tick code  exactly 10, 20, or 30 ms after this event. But sometimes it does, especially under high server load with a lot of entities.

The correct way to do it is to schedule your code to run on the next tick, if you want a delay (the way to do it is to use `MinecraftServer.runAsync` method on 1.16.x, and `MinecraftServer.addScheduledTask` on 1.12.2, the same method also exists on Minecraft instance for the client/render thread)
