### ISSUE TITLE
Cycle Painting also moves painting 2

### ISSUE THREAD

**Issue by Yupoman** [Serilum/.issue-tracker#260]
## **Information**
Minecraft version: 1.16.1
Forge version: 32.0.61/108
Environment: Singleplayer / Multiplayer

Mod name: Cycle Painting Mod
Mod version: 1.3

## **Description**
Similar to [https://github.com/ricksouth/serilum-mc-mods/issues/46](url) but the painting moves down a block (only paintings of a block wide) when i use these mods that add more paints
[https://www.curseforge.com/minecraft/mc-mods/dark-paintings/](url) [https://www.curseforge.com/minecraft/mc-mods/buildersaddition](url)

## **Crash report**
If available.

**Comment by ricksouth** [comment]
Thanks for opening the issue! I've fixed it in version 1.4 of the mod. Don't ask me why, but for some reason when modded paintings are added, 1x2 and 1x1 lower one block. I thought it was just for the Tombstone mod but it's for all modded paintings.

Anyways, fixed in the latest version :)
https://www.curseforge.com/minecraft/mc-mods/cycle-paintings

**Comment by jengendler** [comment]
Do you have plans to update the 1.16.1 version to 1.4 as well?
