### ISSUE TITLE
Anvil enchant transfer

### ISSUE THREAD

**Issue by Mr-Clay** [Serilum/.issue-tracker#263]
## **Information**
????

## **Feature description**
I've had this amazing idea.. Could you make a mod that will allow the transfer of enchants from an item to a book using the anvil.
maybe one enchant at a time and needs XP to transfer the enchant.

**Comment by ricksouth** [comment]
I appreciate the new mod suggestion! I have added your idea to the list. I'm keeping track of all ideas on the Trello page and added the URL of this issue there.

In order to reduce the amount of open issues on this Github repository, I'll be closing this issue.

It definitely does not mean I am not interested and I'll post a comment here if/when the mod is released. This might take some time, as bug reports take priority. But I'll definitely be releasing more mods along the way.

Thank you very much for the suggestion!
