### ISSUE TITLE
Villager trade idea

### ISSUE THREAD

**Issue by RedBaronFlyer** [Serilum/.issue-tracker#266]
(Sorry in advance if this isn't possible. I've never modded Minecraft before.)

## **Information**
Mod name: All Villager Trades Available

## **Feature description**
Hi, I was wondering if it would be possible to have it so that villagers have all their trades based on their trade pool available(when they level appropriately). For example, (taking this from the minecraft wiki) a novice armorer would start with selling:

15 coal = 1 emerald
5 emeralds = 1 iron helmet
8 emeralds = 1 iron chest plate
7 emeralds = iron leggings
4 emeralds = 1 iron boots
Rather than how it works right now with villagers picking two of their trades to offer.

Then, when the armorer levels, they would also all the trades they could have in the next tier, which would be:

4 iron ingots = 1 emerald
36 emeralds = 1 bell
3 emeralds = 1 chainmail leggings
1 emerald = 1 chainmail boot

and so on.

Thanks for reading my suggestion. Sorry if this isn't actually possible.

**Comment by ricksouth** [comment]
I appreciate the new mod suggestion! I have added your idea to the list. I'm keeping track of all ideas on the Trello page and added the URL of this issue there.

In order to reduce the amount of open issues on this Github repository, I'll be closing this issue.

It definitely does not mean I am not interested and I'll post a comment here if/when the mod is released. This might take some time, as bug reports take priority. But I'll definitely be releasing more mods along the way.

Thank you very much for the suggestion!
