### ISSUE TITLE
A disenchanting mod

### ISSUE THREAD

**Issue by Blugori** [Serilum/.issue-tracker#269]
Mod name : Grindstone disenchant
Mod version : 1.16.1 (forge)

Suggestion : I don't really know if you want to create more new "little" mods that upgrade minecraft in a vanilla-friendly way, but I'll try to suggest something.
I saw on curseforge a mod (for fabric) that allows grindstone to transfer enchantments from an item to a book, and it made me thought about your mods, and I realized that they were no one that brings this mechanic. It would be awesome if you could bring it to us for forge !

Best regards :)
link to the fabric version : https://www.curseforge.com/minecraft/mc-mods/grind-enchantments

**Comment by ricksouth** [comment]
I appreciate the new mod suggestion! I have added your idea to the list. I'm keeping track of all ideas on the Trello page and added the URL of this issue there.

In order to reduce the amount of open issues on this Github repository, I'll be closing this issue.

It definitely does not mean I am not interested and I'll post a comment here if/when the mod is released. This might take some time, as bug reports take priority. But I'll definitely be releasing more mods along the way.

Thank you very much for the suggestion!
