### ISSUE TITLE
How to install without the Twitch app

### ISSUE THREAD

**Issue by ghost** [Serilum/.issue-tracker#277]
Minecraft version: 1.16.3
Forge version: 34.1.1
Environment: Singleplayer
Mod name: The Vanilla Experience
Mod version: 2.6

How to install? I'm using a Linux distribution and I can't use twitch curseforge

**Comment by ricksouth** [comment]
<span style="font-size: 18px;"><strong><span style="color: #800000; font-size: 18px;">Here's some information I wrote in the past on how to use MultiMC. Thanks for the interest!</span></strong><br /></span></p>
<div class="spoiler">
<p><span style="font-size: 18px;">Because the Twitch launcher does not support the newest Minecraft version yet, some extra steps are needed until it does. I recommend using the MultiMC launcher until then; it's open-sourced and works well. To get the launcher to work, follow these steps:</span><br /><br /><span style="font-size: 14px;"><strong><br />Download MultiMC from the following page:&nbsp;<a href="https://multimc.org/#Download" target="_blank" rel="noopener noreferrer">https://multimc.org/#Download</a></strong></span><br /><img src="https://i.imgur.com/OSjFQNA.png" /><br /><br /><span style="font-size: 14px;"><strong><br />Once installed, open the launcher. In the top left of the screen click on "Add a new instance."</strong></span><br /><img src="https://i.imgur.com/AP3bI7O.png" /><br /><br /><span style="font-size: 14px;"><strong><br /><br />On the left, click on "Import from zip". Then click on Browse, and point it to the downloaded zip from this page. The zip is called "TheVanillaExperience_1.16-2.3".<br /></strong><em>Direct link to the modpack: <a href="https://www.curseforge.com/minecraft/modpacks/the-vanilla-experience/files/2991406" target="_blank" rel="noopener noreferrer">https://www.curseforge.com/minecraft/modpacks/the-vanilla-experience/files/2991406</a>.</em></span><br /><img src="https://i.imgur.com/c8Ty0wK.png" /><br /><br /><span style="font-size: 14px;"><strong><br />The modpack will now download.</strong></span><br /><img src="https://i.imgur.com/WLdGSiY.png" /><br /><span style="font-size: 14px;"><strong><br /><br />All that's left is to double click the icon that's now in your list. Enjoy! Thank you for downloading!</strong></span><br /><img src="https://i.imgur.com/BVLcF2s.png" /><br /><br /><span style="font-size: 14px;"><strong>Keep in mind that Forge 1.16 is still in beta, and some issues might arise.</strong></span><br /><img src="https://i.imgur.com/bvF95We.png" /></p>
</div>
