### ISSUE TITLE
Older versions

### ISSUE THREAD

**Issue by Maxwelljones** [Serilum/.issue-tracker#279]
Hello, Thank you for such a great mod.
Would you please be so kind and let older versions available on curseforge?
It's very tedious for us modpackers to track what mod has a version that's not available on cf in order to release another build of the modpack. Would be great if you leave older versions available there.
Thank you in advance.

Mod: Collective
MCVersion: 1.15

Best for the future ;)

**Comment by ricksouth** [comment]
I'll leave them be from now on! But the people asking where the 1.12 version has gone are sure to come :) Thanks for using some of my mods.

**Comment by Maxwelljones** [comment]
Thank you <3

**Comment by kreezxil** [comment]
@ricksouth might i suggest that you unarchive (restore) the mods you previously archived on CF. CF doesn't actually delete. Here's a statement I use to educate others on the mechanic.

`
a modder wanting to clean up the list of mods that are actively listed by branch will archive all the mods, not realizing that by doing so only mod packs that have already been approved will be able to download that mod and any new mod packs that had that mod version upon initial inspection will get rejected by cf because the modder removed via the archive method the mod from future new packs.
`
