### ISSUE TITLE
Option to change difficulty after portal creation

### ISSUE THREAD

**Issue by Pentasis** [Serilum/.issue-tracker#287]
Mod: Nether portal spread

This may be way out of scope so don't feel bad rejecting it :) But I thought I'd ask anyway.
The way I usually play is by setting the difficulty to peaceful and change it to normal or hard after I create a nether portal. This gives me time to setup a good start base and it makes sense to me in an RP kind of way (evil spreading into the world through the portal).
It should be optional though as not everyone will like to play like that.

**Comment by ricksouth** [comment]
I don't think I'll add this feature to nether portal spread, but it might be possible to have a separate mod which can change the game's difficulty when certain triggers are reached. Thanks for the idea, and using the mod.

**Comment by Pentasis** [comment]
yw. Thank you for making these mods. A separate mod with triggers would be awesome.

**Comment by ricksouth** [comment]
I appreciate the new mod suggestion! I have added your idea to the list. I'm keeping track of all ideas on the Trello page and added the URL of this issue there.

In order to reduce the amount of open issues on this Github repository, I'll be closing this issue.

It definitely does not mean I am not interested and I'll post a comment here if/when the mod is released. This might take some time, as bug reports take priority. But I'll definitely be releasing more mods along the way.

Thank you very much for the suggestion!
