### ISSUE TITLE
[Starter Kit]Option to randomize starter kit.

### ISSUE THREAD

**Issue by Inpaladin** [Serilum/.issue-tracker#295]
Mod name: Starter Kit
Title.  Would be nice if we could have multiple starter kits that the mod would just randomly pull from on initial spawn.  Could be nice for just adding slight variations like different flavor texts or slightly different items to make different players/playthroughs slightly more unique.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!

**Comment by ricksouth** [comment]
Thank you again for the feature request!

I've been working hard on lots of new features for Starter Kit these past few days. Version 6.0 is now available on CurseForge and Modrinth. It contains many new features, and this one has been added too :) Hope you enjoy them!

https://legacy.curseforge.com/minecraft/mc-mods/starter-kit
