### ISSUE TITLE
Mod Suggestion: Cursed Earth

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Serilum/.issue-tracker#296]
Since you like to write lots of mods, and since Cursed Earth has not been updated since January, might I suggest you either take it over or write your own.

https://www.curseforge.com/minecraft/mc-mods/cursed-earth

Thanks, CM

PS: Keep up the good work!

**Comment by ricksouth** [comment]
I appreciate the new mod suggestion! I have added your idea to the list. I'm keeping track of all ideas on the Trello page and added the URL of this issue there.

In order to reduce the amount of open issues on this Github repository, I'll be closing this issue.

It definitely does not mean I am not interested and I'll post a comment here if/when the mod is released. This might take some time, as bug reports take priority. But I'll definitely be releasing more mods along the way.

Thank you very much for the suggestion!
