### ISSUE TITLE
Needless dependency

### ISSUE THREAD

**Issue by Su5eD** [Serilum/.issue-tracker#305]
## **Information**
Mod name: Wool Tweaks
Mod version: 1.0

## **Comment**
This mod requires a needless dependency - [Collective](https://www.curseforge.com/minecraft/mc-mods/collective). There are no references to it in the code, and the mod runs flawlessly without it. So why would I need it at all?

**Comment by ricksouth** [comment]
Hi, thanks for the interest. About 98% of my mods require Collective. If I ever want to add a functionality to all of them, I have the possibility to do so now. It also make a updating mods to fix issues and to make them work with newer Minecraft versions easier, by knowing what other functions I have access to. That's why my development area by default includes the library mod. It's not some kind of ruse, don't worry.

You can edit the mods.toml file and ignore the dependency if you'd like. Just keep in mind that I might make references to the code in the future.
