### ISSUE TITLE
Suggestion: Separate name pools for different kinds of villager

### ISSUE THREAD

**Issue by Snorps** [Serilum/.issue-tracker#307]
## **Information**
Mod name: Villager Names

## **Feature description**
It would be cool if you could set custom names for the different biome villagers/villagers from different mods. I'd have a lot of fun choosing them all and it would give all the different villagers a unique character.

**Comment by soulhakr** [comment]
slight expansion on this idea:
separate pool for villagers based on job type.
for instance:
I want all my Leatherworker villagers to have the last name "Tanner", 
All my Scribes to have the last name "Booker"
All my Shepherds to be "Shepherd"
All my Armorers to be "Smith"
All my Clerics named "Priest"
etc.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
