### ISSUE TITLE
"default" entry for nether portal spread

### ISSUE THREAD

**Issue by jblosser** [Serilum/.issue-tracker#310]
## **Information**
Mod name: Nether Portal Spread

## **Feature description**
Can we get a "default" replacement entry? e.g.:

default; [netherrack>5 + soul_sand>3 + magma_block>2],

If it's not defined, things behave as they do now. If it is defined, any brick it finds that isn't in the list with a specific entry uses this one.

This would save a whole lot of typing for those of us that want to have the spread hit basically everything.

This might create the need for a default exclusion list, to prevent some blocks from being changed, but I'm fine without that. Note, though, that at least the portal materials themselves, and probably the blocks being used as replacements, need to be immune, so it may be worth adding regardless.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
