### ISSUE TITLE
Choose which village buildings you will spawn with

### ISSUE THREAD

**Issue by Sarsath** [Serilum/.issue-tracker#312]
I have a suggestion for the Village Spawn Point mod.

The mod should allow you to include or exclude selected buildings (the options being "Include", "Exclude", and "I Don't Care") in the village that you will spawn in.

I would really appreciate if you would implement this idea.

**Comment by James103** [comment]
Would that mean that the mod searches for a village whose buildings meet your criteria, or would the mod intercept the village generation process so that the buildings you select to include always generate and buildings you select to exclude never generate?

**Comment by ghost** [comment]
(Reposting this from the other similar request, since I don't know which one is active.)

Referring to the comment above, probably the latter is better, since the mod already slows down world generation, and searching for the perfect village could take ages.

Below is my repost:

I fully support and want this, badly. Maybe it's out of scope, but it would make the mod so much _more_, in general. I always have to copy the buildings from a throwaway world so my villages have all the houses I need.

I will add something, though: If you add this, please do add support for [Charm's restored/additional villages](https://svenhjol.github.io/Charm/sections/world) and [More Villagers' houses/workstations](https://www.curseforge.com/minecraft/mc-mods/more-villagers-fabric).

(Mostly Charm's, since Snowy Taiga villages being exclusive to Bedrock Edition makes me EXTREMELY mildly inconvenienced.)

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
