### ISSUE TITLE
Mod Idea: Random Raids

### ISSUE THREAD

**Issue by ballymacad** [Serilum/.issue-tracker#322]
## **Information**
Mod name: ?

## **Feature description**
I've had this amazing idea for a minimalist mod that I think really fits with the other mods you create. The idea is to make a mod that creates a random chance for a raid to spawn whenever a player wakes up from sleeping in a village. Basically, there is a random chance for players to wake up with the Bad Omen effect. This would turn the game into a village defense game and make raids actually make sense, and if combined with your village spawn point mod could be really challenging! It might also make sense to expand the radius on the bell's glowing effect so that players that are having lots of raids don't get stuck with having one or two random pillages hiding somewhere. 

I'm a huge fan of you mods and don't think I could stand to play the game without Village spawnpoint, Extended bonemeal and your compass/clock mods. Thank you so much for making this game so much more amazing!

**Comment by James103** [comment]
Would the raids always be level 1, or could it be that the level can also be random (perhaps uniformly or based on local difficulty)? For example, random raid level based on local difficulty would make it so the longer you spend in a single village, the more powerful the raiders become on average due to enchantments.

**Comment by ballymacad** [comment]
I think scaling difficulty based on how long you were in the village would be a great idea!! Random would probably be fun too though. I'm partially thinking of this as being part of the trade off of using a village to give yourself a head start early game, but for my play style, needing to continually improve village defenses for increasing raid difficulties would be awesome.

**Comment by ricksouth** [comment]
I appreciate the new mod suggestion! I have added your idea to the list. I'm keeping track of all ideas on the Trello page and added the URL of this issue there.

In order to reduce the amount of open issues on this Github repository, I'll be closing this issue.

It definitely does not mean I am not interested and I'll post a comment here if/when the mod is released. This might take some time, as bug reports take priority. But I'll definitely be releasing more mods along the way.

Thank you very much for the suggestion!
