### ISSUE TITLE
Suggestion: Auto Composter

### ISSUE THREAD

**Issue by redsamme** [Serilum/.issue-tracker#326]
## **Information**
Mod name: Auto Composter

## **Feature description**
I believe composters should take in organic material and only provide bone meal over time. Since it seems you prefer your mods to be drag & drop, perhaps having the composter look in adjacent chests would be better than a built-in storage solution.

**Comment by ricksouth** [comment]
I appreciate the new mod suggestion! I have added your idea to the list. I'm keeping track of all ideas on the Trello page and added the URL of this issue there.

In order to reduce the amount of open issues on this Github repository, I'll be closing this issue.

It definitely does not mean I am not interested and I'll post a comment here if/when the mod is released. This might take some time, as bug reports take priority. But I'll definitely be releasing more mods along the way.

Thank you very much for the suggestion!
