### ISSUE TITLE
Shearable Llamas Mod?

### ISSUE THREAD

**Issue by Areolata7** [Serilum/.issue-tracker#328]
I absolutely love your mods, and use many of them, so I had a suggestion.

It has always bugged me that Llamas cannot be sheared to produce wool blocks the same color as the Llama. Llamas are mostly useless in the game so some Llama improvements would be great.  Shearing is a must but Llama meat would also be useful. Even Llama milk (for food not anti-curse) would be great. Perhaps Llama milk is only collected to turn into butter (or cheese) to use with vanilla bread? That would give specific purpose to Llama milk (vs cow milk).  I just thought it would be great to make Llamas more useful.  I searched around curseforge for any mod that improves Llamas and "milk all the mobs" is the only one that comes even close to my suggestions. I can't find any that allow you to shear Llamas or get meat from them.

**Comment by ricksouth** [comment]
I appreciate the new mod suggestion! I have added your idea to the list. I'm keeping track of all ideas on the Trello page and added the URL of this issue there.

In order to reduce the amount of open issues on this Github repository, I'll be closing this issue.

It definitely does not mean I am not interested and I'll post a comment here if/when the mod is released. This might take some time, as bug reports take priority. But I'll definitely be releasing more mods along the way.

Thank you very much for the suggestion!
