### ISSUE TITLE
[Transcending Trident] Add the ability to configure when Channeling works.

### ISSUE THREAD

**Issue by Inpaladin** [Serilum/.issue-tracker#335]
## **Information**
Mod name: Transcending Trident

## **Feature description**
Would be nice to be able to have a more flexible version of Channeling, and I feel like it would fit well with the spirit of this mod, even if it's not directly related to riptide.  The config could have the option to set Channeling to work normally, during any rain, or any time.  Some bonus options could be a dimension and biome blacklist, although I'd imagine that could be a bit of a nightmare to implement.

**Comment by James103** [comment]
To expand on that:
* A similar mod idea could be implemented, but affecting Riptide instead.
* Instead of just a blacklist, the configuration could be per-biome and per-dimension. in other words, allowing Channeling and/or Riptide to work either not at all, as normal, during any rain, or always on a per-biome and/or per-dimension basis.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
