### ISSUE TITLE
Mining with a RFTools builder

### ISSUE THREAD

**Issue by dkbhn** [Serilum/.issue-tracker#342]
## **Information**
Minecraft version: 1.16.4
Forge version: 25.1.12
Environment: Probably both Singleplayer and Multiplayer

Mod name: Mineral Chance
Mod version: 1.0

## **Description**
I've set up a RFTools builder as a quarry/miner in nether to mine for nether quartz and Ancient debris. I mined an area of 512x120x512 which worked fine, exept from, in that same area there we're scattered gold nuggets, nether Quartz and neterite scrap all over, which is the things you get from MineralChance.
The server was lagging like crazy, and when I went into the nether I found out why, there we're liturally hundreds of thousands floating items, in the mined area.

## **Crash report**
This is not a crash, just a FYI.

**Comment by James103** [comment]
I bet the RFTools builder uses a fake player to perform the block breaking action, which procs Mineral Chance and has a chance of dropping a mineral (as an item) even though you yourself didn't mine that block. As the area being mined is well over 30 million blocks in volume (of which about 1/2 could be all netherrack), it creates all those item entities because Mineral Chance is proc'd for every netherrack block mined, even if it was a fake player.

Possible fix: Remove fake player support from Mineral Chance (by default if config option).

**Comment by dkbhn** [comment]
So that's something that you might ad to the config?

**Comment by ricksouth** [comment]
Thanks for using the mod and submitting the bug report! Sorry for the inconvenience about the lag. Version 1.2 adds the config option 'ignoreFakePlayers' which is enabled by default. That should fix the problems you were having.

https://www.curseforge.com/minecraft/mc-mods/mineral-chance
