### ISSUE TITLE
Full Screen Advancements

### ISSUE THREAD

**Issue by leyxcx** [Serilum/.issue-tracker#343]
## **Information**
Mod name: Full Screen Advancements

## **Feature description**
The small advancements screen can be annoying when it comes to setting up and easily viewing custom advancements in modpacks. The only mod I could find that does anything like this is for Fabric, which is disappointing. Further idea would be maybe adding an advancements tab directly to the inventory screen for easier access (truthfully I don't know if any 1.16 mod does this at the moment because the modding scene is a mess right now). I hope this makes sense, it'd be a great QOL mod outside of bigger modpacks as well :)

**Comment by SlayDigger** [comment]
https://www.curseforge.com/minecraft/mc-mods/better-advancements

**Comment by ricksouth** [comment]
I appreciate the new mod suggestion! I have added your idea to the list. I'm keeping track of all ideas on the Trello page and added the URL of this issue there.

In order to reduce the amount of open issues on this Github repository, I'll be closing this issue.

It definitely does not mean I am not interested and I'll post a comment here if/when the mod is released. This might take some time, as bug reports take priority. But I'll definitely be releasing more mods along the way.

Thank you very much for the suggestion!
