### ISSUE TITLE
Increases cap for enchant level ?

### ISSUE THREAD

**Issue by Alien10123** [Serilum/.issue-tracker#344]
## **Information**
Minecraft version: 1.16.3
Forge version: 35.1.13
Environment: Singleplayer 

Mod name: Enchanting Commands
Mod version: 1.3

## **Question**
Is there any way to increases the cap enchant level of 127? I would like to set the level to something like 10000.

**Comment by James103** [comment]
In general, Minecraft supports enchantment levels up to 2,147,483,647, though some other sources may claim that the maximum enchantment level is 255 or 32,767 even with commands.

**Comment by Alien10123** [comment]
> In general, Minecraft supports enchantment levels up to 2,147,483,647, though some other sources may claim that the maximum enchantment level is 255 or 32,767 even with commands.

When i use the /ec command and i try to make the enchant level more then 127 it doesn't work. Here is the command i am trying to do:
/ec enchant sharpness 1000
I am holding a sword in my hand and the error says that the enchant level can not be more then 127. How can i get big enchant levels?

**Comment by Kisonu** [comment]
allowing for higher enchanting levels would be an awesome feature, for fabric modloader as well. IDK if this is veing considered to what, but even 255 seems like a more... rounded option.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
