### ISSUE TITLE
Auto Message Mod (or additional content for the First Join Mod)

### ISSUE THREAD

**Issue by Patrick1417** [Serilum/.issue-tracker#365]
## **Information**
Mod name: Auto-message Mod

## **Feature description**
Im thinking about a mod that can automaticaly post preset messages (like 20 sentences in a .txt file) in the Chat, every 5 minutes or so. 
So that the Server Admins can spread informations for all the people playing.

Thanks.

**Comment by James103** [comment]
This can be done via a datapack by putting the following commands in a function file, installing it as part of a datapack, then running `/function namespace:path/to/function`:
```mcfunction
tellraw @a "The message to broadcast"
schedule function namespace:path/to/function 300s
```
(where `300s` can be replaced with the actual frequency you want to broadcast the message)

**Comment by ricksouth** [comment]
I appreciate the new mod suggestion! I have added your idea to the list. I'm keeping track of all ideas on the Trello page and added the URL of this issue there.

In order to reduce the amount of open issues on this Github repository, I'll be closing this issue.

It definitely does not mean I am not interested and I'll post a comment here if/when the mod is released. This might take some time, as bug reports take priority. But I'll definitely be releasing more mods along the way.

Thank you very much for the suggestion!
