### ISSUE TITLE
Better Bell Idea

### ISSUE THREAD

**Issue by SlayDigger** [Serilum/.issue-tracker#367]
## **Information**
Mod name: Better Bell

## **Feature description**
I'm currently working on a pack that includes Savage and Ravage as well as Dungeon Mobs (https://www.curseforge.com/minecraft/mc-mods/savage-and-ravage https://www.curseforge.com/minecraft/mc-mods/dungeons-mobs) and I noticed that the Bell ringing in Vanilla really sucks. It only works if there is a pillager within 32 blocks, only shows mobs in a 48 block radius, and only lasts for a few seconds. This turns the challenge of a raid from Fighting Mobs into instead Finding Mobs, some of which can be in caves, stuck, in lakes, ect. Here is my idea: A mod that improves upon these bells greatly. When the bell is rung by a player, all mobs part of the raid will have the glowing effect and particles until they die. This would make finding lost stragglers easy and allow you to get back to the fight as fast as possible.

**Comment by ricksouth** [comment]
I appreciate the new mod suggestion! I have added your idea to the list. I'm keeping track of all ideas on the Trello page and added the URL of this issue there.

In order to reduce the amount of open issues on this Github repository, I'll be closing this issue.

It definitely does not mean I am not interested and I'll post a comment here if/when the mod is released. This might take some time, as bug reports take priority. But I'll definitely be releasing more mods along the way.

Thank you very much for the suggestion!
