### ISSUE TITLE
End stone Version

### ISSUE THREAD

**Issue by WilliamBlaze** [Serilum/.issue-tracker#369]
there's been a few mods out there for a while now that let players create end portal frames to create their own end portals anywhere they wish. I think it would be really neat if we had a version of this very mod that would cause endstone to generate/replace the default blocks on the ground beneath and around such endportals - maybe even cause active endportals in strong holds to start converting the blocks and lava below them into endstone in a similar fashion to how netherack is generated near and around nether portals from the nether portal spread mod?

Just a neat thought to consider because of how this mod works!

**Comment by ricksouth** [comment]
I appreciate the new mod suggestion! I have added your idea to the list. I'm keeping track of all ideas on the Trello page and added the URL of this issue there.

In order to reduce the amount of open issues on this Github repository, I'll be closing this issue.

It definitely does not mean I am not interested and I'll post a comment here if/when the mod is released. This might take some time, as bug reports take priority. But I'll definitely be releasing more mods along the way.

Thank you very much for the suggestion!
