### ISSUE TITLE
doors break presser plats

### ISSUE THREAD

**Issue by FullMetalMaster** [Serilum/.issue-tracker#379]
doubledoors_1.16.4-2.1

for some reason when you step on a pressure plate it doesn't open the door and when you step off that it opens the door but you stepped back on it and it closes the door, the state will never be opening the door even if you have the door open already previously it just doesnt work it still only closes the door when your on the presser plat which is not correct

**Comment by ricksouth** [comment]
I wasn't able to replicate your issue. It might have been an incompatibility with another mod. Check out version 2.2 I just uploaded to see if that slves your problem. Otherwise please open another issue with more information pictures/log etc. Thanks for using the mod!

https://www.curseforge.com/minecraft/mc-mods/double-doors
