### ISSUE TITLE
Skeleton/Zombie Horse Mod burn with armor on

### ISSUE THREAD

**Issue by Oriansenshi** [Serilum/.issue-tracker#385]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.16.4
Forge version: 35.1.32
Environment: Multiplayer

Mod name: Zombie Horse Spawn/Skeleton Horse Spawn
Mod version: x.x

## **Question**
I am running a multiplayer server and do not want to overload the server with entities, but i do want to reward my players for getting a zombie/skeleton horse without killing the horse. I understand that by default they burn in the sun. Skeletons and Zombies dont burn in the sun if they have a helmet on, it just eats away at the durability of the helmet, till it breaks and then they burn. Horse armor doesnt use durability, so is there a way that the skeleton/zombie horses can burn in the daylight, but wont burn if you have armor on them? Or is that already a thing and i just completely missed it?

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
