### ISSUE TITLE
Clock GUI time issue

### ISSUE THREAD

**Issue by AechtRob** [Serilum/.issue-tracker#39]
## **Information**
Minecraft version: 1.12.2
Forge version: 14.23.5.2847
Environment: Singleplayer [not tested Multiplayer]

Mod name: GUI Clock
Mod version: guiclock_1.12-1.3.jar

## **Description**
After a few day/night cycles the clock starts displaying garbage minecraft times. Sleeping seems to confuse it. This is without doing a "/time set" command at all. I have had readings of things like 87:30, and at the moment it thinks daybreak is 10.30. It seems to be being completely random. I think some kind of hard-reset may be needed once per minecraft day to keep it in sync? (This would also then accommodate setups with irregular day-lengths possibly)

**Comment by ricksouth** [comment]
This has been fixed in version 1.4 a while ago, but only for 1.14+. I'm sorry for the inconvenience, but I won't be updating older versions anymore.

I'm following the Forge LTS standard: [https://www.minecraftforge.net/forum/topic/79304-112114-and-lts-system/](https://www.minecraftforge.net/forum/topic/79304-112114-and-lts-system/)
