### ISSUE TITLE
Fixed Anvil Repair Cost - is it possible to have the repair cost increase but reach a fixed ceiling value?

### ISSUE THREAD

**Issue by sciguyryan** [Serilum/.issue-tracker#390]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.16.x
Forge version: 36.0.01
Environment: Singleplayer

Mod name: Fixed Anvil Repair Cost
Mod version: 1.1

## **Question**
Is it possible to have the repair cost increase but reach a fixed ceiling value? For example, is it possible to configure things such that the level cost will continue to increase until it reaches 30 and then remain there regardless of how many times it is repaired?

If not, would it be fine for me to add this as a feature request?

Thanks in advance.

**Comment by ricksouth** [comment]
Currently not possible but I'll consider it as a feature. Thanks!

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
