### ISSUE TITLE
Humbling Bundle - Act as if mob killed twice instead of just doubling drops

### ISSUE THREAD

**Issue by James103** [Serilum/.issue-tracker#393]
## **Information**
Mod name: Humbling Bundle

## **Feature description**
What if, when you killed a mob, it was as if you killed 2 of the exact same mob, instead of just acting as if you killed 1 of the exact same mob and doubling any resulting mob drops?

This could, for example, give an increased chance for Zombies to drop an Iron Ingot (and a much smaller chance to drop 2), instead of just preserving the chance for Zombies to drop an iron ingot, but dropping 2 iron ingots instead of 1.

Additionally, with this change, Skeletons would now be able to drop 0, 1, 2, 3, or 4 bones (and same for arrows), instead of just 0, 2, or 4.

**Comment by TheDeviantCrafter** [comment]
This should be as simple as rolling the loot table twice. It would also fix #117 for good.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
