### ISSUE TITLE
Mod conflict with Minecolonies?

### ISSUE THREAD

**Issue by Moleculor** [Serilum/.issue-tracker#403]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.0.13
Environment: Singleplayer, though it causes a disconnection at a minimum in multiplayer as well.

Mod name: Areas
Mod version: v1.1

Additional mod: Minecolonies v596 and Structurize v113 (required for Minecolonies v596)

## **Description**
I built a Medieval Dark Oak style warehouse. It comes with a sign labeled something like "Courier hut block goes here". Not actually those words, but that's what it's trying to say. 

I then used the build tool to place a Courier hut block from Minecolonies where the sign existed, and boop, the server crashed. (In multiplayer it sorta looks like it "just" disconnected me? I didn't even bother trying to reconnect, just rebooted the server while I recreated the bug in singleplayer. 

## **Crash report**
https://gist.github.com/Moleculor/b30b0b76ba70bb92c09167a01c76fa27

## **Related**
https://github.com/ldtteam/minecolonies/issues/6480

**Comment by ricksouth** [comment]
Thanks for submitting the bug report and using the mod! The problem should be fixed in version 1.2 of Areas, please let me know if the problem persists. As I wasn't able to replicate it locally, but figured out where the problem was from your crash report.

https://www.curseforge.com/minecraft/mc-mods/areas
