### ISSUE TITLE
Can't remove repaired tool from Anvil GUI with zero repair cost

### ISSUE THREAD

**Issue by GrumpyChunks** [Serilum/.issue-tracker#411]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.0.14
Environment: Singleplayer

Mod name: Fixed Anvil Repair Cost
Mod version: 1.16.5-1.2

## **Description**
I have changed this option (and only this option)`repairCostLevelAmount = 0`, the anvil GUI on first appearance, looks to be correct, however I can't remove the repaired tool from the slot on the right of the GUI.

<img width="966" alt="Screenshot 2021-02-05 at 09 59 09" src="https://user-images.githubusercontent.com/1747010/107019322-6e1d4000-6799-11eb-9f36-1872542bf5ca.png">

I've tested this with no other mods installed (except the required library mod).

## **Crash report**
n/a

**Comment by ricksouth** [comment]
Thanks for submitting the bug report! This might not be the solution you'd like, but unfortunately due to the vanilla code limitations the minimum level cost has to at least be 1. I've changed the minimum config values to represent this, so the issue doesn't occur anymore, but it does mean that you can't accomplish what you wanted. Sorry for the inconvenience. I've fixed it in version 1.3 of the mod.

https://www.curseforge.com/minecraft/mc-mods/fixed-anvil-repair-cost

**Comment by GrumpyChunks** [comment]
I guessed it might have been an upstream issue, but thanks for looking in to this and responding. I've been using a value of 1 since I raised the report and it works great, really love the mod.

I think I know the answer to this already, but I don't suppose the value would work as a floating point, allowing the player to use a value of >0 && <1, thus allowing the minimal impact on XP , i.e. 1 XP point rather than 1 XP level - if that makes sense? That said, it isn't hard to obtain 1 XP level, so I'd completely understand not wanting to implement this, even if it was possible.
