### ISSUE TITLE
Mineral Chance feature idea

### ISSUE THREAD

**Issue by poisax** [Serilum/.issue-tracker#426]
## **Information**
Mod name: Mineral Chance

## **Feature description**
Making what drops configurable! I'm on 1.12 and use FutureMC, which also adds netherite scraps that I'd love to have a tiny, tiny chance of dropping from netherrack

**Comment by Mikeagan** [comment]
I like this idea as well, although I am using Fabric 1.19 22w13a
Another thought along this line would be to make some items more common than others. You could even add coal as another drop to dilute better drops such as diamonds.
Example:
9 chances each for Iron Nuggets and Gold Nuggets 
5 chances each for Redstone and Lapis Lazuli and Coal
1 chance each Diamond and Emerald

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
