### ISSUE TITLE
[Areas] Randomly generate names for areas.

### ISSUE THREAD

**Issue by RedMoikle** [Serilum/.issue-tracker#435]
## **Information**
Mod name: Areas

## **Feature description**
Add a button/dropdown/menu to generate names for the areas, with options for different kinds of names (village/forest/castle/mountain/insert biome type etc.)

**Comment by Corvus20** [comment]
Rather, doing it automatically would just be nice. Having them automatically gain a name without a need for a sign to be there would be really cool.

**Comment by rikosama** [comment]
really like this idea, especially for villages

**Comment by ricksouth** [comment]
Version 1.4 adds a random name generation feature if the name on the sign is left empty. I'm keeping the issue open for the other suggestions. Thank you!

https://www.curseforge.com/minecraft/mc-mods/areas

**Comment by ricksouth** [comment]
@rikosama I've created this mod (https://www.curseforge.com/minecraft/mc-mods/random-village-names) which assigns randomized names to all villages in the world. It uses the Areas mod to display them. Basically just a sign is placed in the center of the village, which Areas parses.

**Comment by HeroMeDavid** [comment]
would it be possible to add names to a config file of names that a village could have?

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
