### ISSUE TITLE
Configure Water Bucket out

### ISSUE THREAD

**Issue by Freshah** [Serilum/.issue-tracker#450]
## **Information**
Mod name: Transcending Trident

## **Feature description**
Hello, I'm building a pack and absolutely love using this mod w/ Quark and an Elytra in late endgame.  But for balance reasons I was hoping to gate this mod's abilities behind a modded item in place of the water bucket, or even something like Heart of the Sea.

Being able to hook this mod's functions to any item would be lovely for pack makers.

Apologies for my bad formatting I'm on mobile at the moment and am new to Git.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!

**Comment by Freshah** [comment]
Your last message here in August was sufficient.

I didn't mean to hurt your feelings with whatever Discord comment of mine you saw or were told about. 
Judging by this timing, it did make its way to you and I want you to know if it was actual, serious criticism, it'd be communicated to you more directly.

I was just frustrated that not every mod is as configurable as Quark, and that's a weird and unrealistic standard to push on mod authors.

Make your mods the way you want, it's not a big deal or a genuine problem.

I personally don't use TT anymore so that's why I never followed up with this myself.

**Comment by ricksouth** [comment]
Looks like it's a coincedence, as I haven't read any Discord message. But I appreciate it :) No worries, I'll still leave it open as a feature request.
