### ISSUE TITLE
Disable Poisonous Damage Modifier

### ISSUE THREAD

**Issue by Decycle** [Serilum/.issue-tracker#454]
**Mod name: Altered Damage**

Currently, poisonous damage could sometimes kill the player if the damage modifier is set to be higher than 1. It would be great if the damage modifier won't work on poisonous damage, or increase the cap when you start to take poisonous damage. For example, if the damage modifier is set to 3x, stop taking poisonous damage when the player's health is below 3 health, instead of 1.

**Comment by ricksouth** [comment]
Thanks for submitting the issue and using the mod! I've added the config option 'preventFatalModifiedDamage' in version 1.3 which should fix the problem you were having. When the extra damage is fatal which otherwise wouldn't the modifier is removed. This prevents dying from poison and starvation due to the modifier.

https://curseforge.com/minecraft/mc-mods/altered-damage
