### ISSUE TITLE
There should be named biomes

### ISSUE THREAD

**Issue by DcNdrew** [Serilum/.issue-tracker#459]
## **Information**
Mod name: Areas

## **Feature description**
As in Named Areas before, there should be named biomes. By the way, is there any difference between prefixes (area, zone, region)?

**Comment by ricksouth** [comment]
The feature was using a lot of processing power to accomplish the named biomes. I'll try to do it in a better way when I have time. Thanks for opening the issue and using the mod!

Those prefixes all the the same. It's just what you prefer :)

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
