### ISSUE TITLE
Crash, name in crashfile log

### ISSUE THREAD

**Issue by axalox** [Serilum/.issue-tracker#475]
## **Information**
Minecraft version: 1.12.2
Forge version: 1.12.2 - 14.23.5.2854
Environment: Multiplayer

Mod name: skeletonhs_1.12-1.1.jar
Mod version: 1.12-1.1

## **Description**
Server crash

## **Crash report**
[crash-2021-02-28_21.31.24-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/6057947/crash-2021-02-28_21.31.24-server.txt)

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try. Unfortunately due to the code change in 1.14 I wasn't able to reproduce fixes I've made for the Spawn mods in version 1.12.

I've just archived the 1.12 and 1.13 files for all the Spawn mods so others won't have this problem anymore. Sorry for the inconvenience. I understand it's not the answer you'd like to hear.
