### ISSUE TITLE
Empty NBT tags on all CEMD drops

### ISSUE THREAD

**Issue by FloorIsTired** [Serilum/.issue-tracker#482]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.0.43
Environment: Multiplayer

Mod name: Configurable Extra Mob Drops
Mod version: 1.3

## **Description**
Howdy been messing around with adding and creating custom mob drops on a modded server I have and I've found items that are added to a mob's drop list have empty NBT tags which messes with interactions with mods like digital storage. For example I had added coal to a zombified piglin's loot table however if I put the piglin's coal into a Refined Storage digital storage system autocrafting recipes and other mods will view the coal as a separate type because of the NBT tag and will ignore it. I was wondering if there is a way to remove the NBT tags on the CEMD drops because other natural mob drops don't have these nbt tags.

From what I've tested its added empty NBT tags to every item added with CEMD. Which causes conflicts with mods that view items with any NBT as a different type of item.

I am using the op commands for adding drops to loot tables as well if that matters.

**Comment by ricksouth** [comment]
Thanks for submitting the issue and using the mod! This has been fixed in version 1.4 of the mod. I did have code to remove the nbt tag, but not to remove the empty "nbt tag-tag" from the itemstack. Everything should stack no problem now.

https://www.curseforge.com/minecraft/mc-mods/configurable-extra-mob-drop
