### ISSUE TITLE
FARC - Making the anvil repair a certain amount of durability per action instead of percentage

### ISSUE THREAD

**Issue by ChromaPIE** [Serilum/.issue-tracker#486]
## **Information**
Mod name: Fixed Anvil Repair Cost

## **Feature description**
As has been said in the title, it would probably make it more suitable, and more fine-tuning-friendly for packs valuing balance. Like, always setting one single iron ingot to be able to only contribute, like 100 points of durability would undoubtedly be more balanced than making it repair 33.3% of the whole regardless of the repaired item having just 10 uses, or 10000.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
