### ISSUE TITLE
Feature: Ability to change the list of town names used for Random Village Names

### ISSUE THREAD

**Issue by James103** [Serilum/.issue-tracker#497]
## **Information**
Mod name: Random Village Names

## **Feature description**
What if players could configure the list of names that are used when placing village name signs? The mod could read a file, which consists of a list of names each separated by line breaks, and use that to generate the village names.

For example, some players may want mainly Italian names, while others may want mainly British names, and yet others may still want Chinese or Japanese names. Having the ability to read village names from a file can allow for that to happen.

(By the way, where do you get the default town name list from? I can't find it within the mod itself.)

**Comment by ricksouth** [comment]
I'm planning on creating a central functionality for it within Collective. That's where the current town name list is included. I'll have to update Pet Names as well. It'll be based on the Villager Names functionality.

Thanks for the suggestion!

**Comment by Nicknaem** [comment]
👍

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
