### ISSUE TITLE
Is there a way to hide an empty hand?

### ISSUE THREAD

**Issue by ghost** [Serilum/.issue-tracker#505]
Is there a way to hide an empty hand without hiding it all the time? So if I'm carrying something I see the hand/item but if I'm not I don't. (It always seemed weird to walk around holding out my empty hand.)

**Comment by ghost** [comment]
Oh, the mod is Hide Hands.

**Comment by ricksouth** [comment]
There is not, but I'll add it in a future release. Thanks for submitting the idea!

**Comment by cloridon** [comment]
Any updates on this feature?

**Comment by TheJessaChannel** [comment]
Please add this feature, particularly to 1.16.5. Thank you.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
