### ISSUE TITLE
QOL Nether Starting Mod

### ISSUE THREAD

**Issue by leyxcx** [Serilum/.issue-tracker#507]
Mod name: Nether Start/Spawn/Beginning

With 1.16 I feel like this should've been added to vanilla for QOL, considering it's fully possible to at least have a full starting experience within the new Nether before going to the Overworld. There's one mod already existing that does this, but the dev has disappeared for over half a year now and with the mod being all rights reserved republishing with an updated mods.toml isn't possible. I also think this is probably in line with your other mods being QOL. (An optional End start (more for modpack developing) could be interesting too :D)

**Comment by ricksouth** [comment]
I do like that! It's on the list, thanks.

**Comment by James103** [comment]
I don't know if this should be separate mods, but what if the "Nether Spawn" (or similar name) mod you're planning to implement had a config that allowed you to choose which dimension you spawn in? For example, a bee-oriented modpack could use the mod to start you off in the Bumblezone, whereas [Levitated modpack](https://www.curseforge.com/minecraft/modpacks/levitated) (if it ever gets remade for 1.16+) could use the mod to start you off in the End.

**Comment by ricksouth** [comment]
That could work. How would you determine what biome you'd spawn in? Or always centered?

**Comment by ricksouth** [comment]
I appreciate the new mod suggestion! I have added your idea to the list. I'm keeping track of all ideas on the Trello page and added the URL of this issue there.

In order to reduce the amount of open issues on this Github repository, I'll be closing this issue.

It definitely does not mean I am not interested and I'll post a comment here if/when the mod is released. This might take some time, as bug reports take priority. But I'll definitely be releasing more mods along the way.

Thank you very much for the suggestion!
