### ISSUE TITLE
Potions, milk buckets, and stews sometimes don't return their containers.

### ISSUE THREAD

**Issue by whatisagoodusername5256** [Serilum/.issue-tracker#540]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.1.4
Environment: Singleplayer

Mod name: Stack Refill
Mod version: 1.7

## **Description**
I noticed whenever I use a drinkable item, (like milk buckets or potions), I sometimes don't get the empty bottle or bucket back. I have narrowed down when this happens, however. If there is an empty space in the hotbar to the left of the item being used, you will get the container back. If you already have an empty container anywhere in your inventory, (provided it isn't a full stack of that item), you will also get the container back. Lastly, if you only have one of the drink you are using left, (the one you are using), you will get the container back. Other than those exceptions, the container is effectively deleted.

Another note, food items like stews that return bowls also do this, but the only exception is the last one mentioned above (only have one stew left before used).

## **Crash report**
None

**Comment by VioletDreamers** [comment]
Not sure the rules about bumping old threads, but having the same issue. Sucks because I like a full inventory before emptying it, and I've lost 6 bowls already :(

(Also playing 16.5, whatever Forge is automatically rec'd for 16.5, and the newest version of the mod).

**Comment by Ceimnithe** [comment]
Also having this issue on 1.18.2 with the latest version of forge (40.1.0) and the mod lol. Keeps taking me potion bottles :(

**Comment by Lonemind** [comment]
I'd also like to confirm this issue. It seems to happen with soup and stew items as well. I'd also like to confirm that it has persisted through to 1.18.2.

**Comment by Wilevar** [comment]
Reporting the same issue in 1.19, but on Fabric modloader.

In my case, eating a bowl of mushroom stew did return the bowl, but then removed a full bowl in my inventory.

Odds are, the stack refill function happened _before_ the bowl return function, but the bowl return function targeted the same hotbar slot and overwrote what was there rather than checking if the slot was open, since default Minecraft would assume the slot to be available.

Some potential solutions:
- Have the stack refill just blacklist any item that returns an item on use.
- Stack refill could be delayed for such items, to give the return function time to give the empty bowl back. Then run a check on the target hotbar slot, and if empty refill as normal. If hotbar slot contains an empty bowl, and the target refill object is something that would return a bowl, then swap it.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! Apologies this took so long for me to get to. This has been fixed in version 3.0 of Stack Refill.

https://www.curseforge.com/minecraft/mc-mods/stack-refill
https://www.curseforge.com/minecraft/mc-mods/stack-refill-refill
