### ISSUE TITLE
Double doors don't open

### ISSUE THREAD

**Issue by kamcknig** [Serilum/.issue-tracker#556]
I'm using the latest version and when I place two spruce doors next to each other, they don't open together. Arre there other requirements for blocks around them or anything?

The mod shows that it is loaded in the main mods menu, but I see no configuration options for it in the options either

**Comment by ricksouth** [comment]
I've tested it locally and on a server, and couldn't find any issues. It's been a while since you've opened the issue, but if you're still using the mod please update to the latest version of Forge, Collective and Double Doors. Let me know if the problem persists with a bit more information on what versions you have so I can take a better look. Thanks for giving the mod a try!
