### ISSUE TITLE
[Areas] Permission System?

### ISSUE THREAD

**Issue by LuxPoseidon** [Serilum/.issue-tracker#557]
## **Information**
Mod name: Areas

## **Feature description**
A basic permission system with the owner of the sign allowing other players to do specific actions within the territory. I know there are other mods that add permissions to claimed land like this. Having it within this mod, however, would make it feel almost vanilla and I really like that about the Areas mod; could make a config option to disable the system for those who don't wish to use it.

**Comment by ClaudiusMinimus** [comment]
This would be a wonderful feature to add, especially in 1.17 as there are no protection mods available at the time of this post. Protection against mod griefing would be nice too.

**Comment by tungstonminer** [comment]
+1 to this feature idea.  I really miss the [Banner Protection](https://lotrminecraftmod.fandom.com/wiki/Banner) system in the LotR mod.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
