### ISSUE TITLE
Change an Area's RGB code by using commands/functions

### ISSUE THREAD

**Issue by EpicDRC** [Serilum/.issue-tracker#566]
Minecraft version: 1.16.4
Forge version: 35.1.4
Environment: Singleplayer and Multiplayer

Mod name: Areas
Mod version: areas_1.16.4-1.1

Hi, I was wondering if there's any way to change an Area's RGB code to change the color of its display when entering/leaving by using commands/functions.

I've already set up multiple [area] signs and I'm trying to set up some sort of function that changes its rgb code when an advancement is triggered. I've tried using:

-/setblock replace/destroy setting the same sign but with a different rgb code, this method only works when there's no block in place or its a regular sign with nothing written in it. If theres already an [area] sign it visually gets changed but the Area message is still the same.

-/setblock air replace/destroy or /fill air, same thing as above happens

The only way I've found is destroying the old [area] sign by hand and then placing another one, but I want to automatize the process using some sort of function.

Thanks for the awesome mod.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
