### ISSUE TITLE
Hunger in peaceful

### ISSUE THREAD

**Issue by foxanthony1** [Serilum/.issue-tracker#568]
## **Information**
Mod name: Hunger in peaceful

## **Feature description**
I've had this amazing idea..

Not so amazing really, I've seen it before. You seem to be the guy because you won't add a bunch of tools and ores and other nonsense. Thanks for your mods, they are a pack dev's dream.

**Comment by James103** [comment]
The similarly-named [Hunger In Peace](https://www.curseforge.com/minecraft/mc-mods/hunger-in-peace) mod has not been updated since 2017 and is only available for MC versions up to 1.12.2, hence the suggestion to create a new mod named "Hunger in Peaceful" so that the idea can be updated to modern versions (MC 1.16.x and beyond).

**Comment by ricksouth** [comment]
I appreciate the new mod suggestion! I have added your idea to the list. I'm keeping track of all ideas on the Trello page and added the URL of this issue there.

In order to reduce the amount of open issues on this Github repository, I'll be closing this issue.

It definitely does not mean I am not interested and I'll post a comment here if/when the mod is released. This might take some time, as bug reports take priority. But I'll definitely be releasing more mods along the way.

Thank you very much for the suggestion!
