### ISSUE TITLE
Idea: Golem tweaks

### ISSUE THREAD

**Issue by NixityNull** [Serilum/.issue-tracker#573]
Mod idea: Golem tweaks (name is not necessarily final)

I've got a few ideas on how to make golems better you might be able to implement.

- Player-made iron golems spawn with pumpkins on their heads
- Pumpkins should be able to be placed back on after being sheared. Golems with pumpkins will follow you, while golems without will wander. Golems will stay stationary if given an undecided mid-game item (possibly nether quartz or glowstone)
- chance for snow golem to spawn naturally in a village in or near a cold biome (naturally spawned golems would not have pumpkin heads)
- snow golems apply potion effects to snowballs if inflicted, same way that creeper explosions leave area effect clouds if they have potion effects on them when they explode
- villagers (more specifically armorers and weaponsmiths due to their association with iron) will repair golems if they are low on health and there are no threats nearby
- repair snow golems with snowballs and snow blocks
- Give snow golems hot biome resistance, absorption and regeneration with blue or packed ice, making them harder to kill and more effective against undead mobs. The effect will only last for a short time, to balance it, as blue ice isn't that hard to get and packed ice is craftable. The hot biome resistance should be permanent though.
- Give Iron golems absorption and regeneration with a totem of undying and/or give them lightning/fire aspect abilities with a nether star, which provides a balanced way to upgrade your golems and even create charged creepers to farm mob heads with. The effect should last for a short time to balance it.

**Comment by ricksouth** [comment]
I appreciate the new mod suggestion! I have added your idea to the list. I'm keeping track of all ideas on the Trello page and added the URL of this issue there.

In order to reduce the amount of open issues on this Github repository, I'll be closing this issue.

It definitely does not mean I am not interested and I'll post a comment here if/when the mod is released. This might take some time, as bug reports take priority. But I'll definitely be releasing more mods along the way.

Thank you very much for the suggestion!
