### ISSUE TITLE
Minor improvement to the GUI Clock mod

### ISSUE THREAD

**Issue by ThatDisappointmentErik** [Serilum/.issue-tracker#578]
The base mod is perfect for its use but you could add an optional setting to allow the clock to display the names of the times of the day.

For example, shown below is the estimated times of day in Minecraft

![image](https://user-images.githubusercontent.com/65751519/119058782-a33e4e80-b994-11eb-9695-c3263754fb3b.png)
![image](https://user-images.githubusercontent.com/65751519/119058814-afc2a700-b994-11eb-9b1f-a7fe8151a45d.png)

All that would need to be added is a toggleable option to allow these names of the times of day to be shown with the time. This could be very beneficial to mods and mod packs that have set times when certain things can spawn. For example, Pixelmon with this mod could make finding certain ores like dawn/dusk ore easier and could make farming things like legendaries easier with knowing the times that they can spawn by chance.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
