### ISSUE TITLE
Set Spawn Underground?

### ISSUE THREAD

**Issue by fenrir6969** [Serilum/.issue-tracker#584]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.1.24
Environment: Singleplayer
Mod: set worldspawnpoint

## **Question**
I want to set the world spawn underground. So, I set the Y coordinate to be 32, smack dab in the middle of the ground, and assumed it would generate a spawn that was at that coordinate. It didn't, im still on the surface. Is this a bug? Or do I just not understand how the mod works-
Is what I'm hoping to do even possible?
Some help would be very much appreciated.

**Comment by James103** [comment]
Have you set `_forceExactSpawn = true` in the config files for the mod?

**Comment by fenrir6969** [comment]
yes. I restarted minecraft to see if that was the problem, which fixed it i guess? But now I'm spawning in solid stone- Which is less than optimal.

**Comment by fenrir6969** [comment]
Wait- Okay i tried another world and its working??? I think-

**Comment by fenrir6969** [comment]
It seems to work maybe 20% of the time, which is sub optimal. Is there a more reliable way to do that?

**Comment by James103** [comment]
Not all worlds generate a cave underground near/at the requested world spawn point. If there are no caves near the requested world spawn point, you will spawn on the surface as that's the nearest air pocket to the requested world spawn.

**Comment by fenrir6969** [comment]
Is it possible to Not specify X and Z? i dont really care about those factors, Just The Y level.
Perhaps 32 is a bit too high, occasionally it spawns me on the bottom of the ocean floor lol. So uh- perhaps 25 could get me more consistent results?

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!
