### ISSUE TITLE
A mod that makes skeletons spawn with sword, sword + shield, and nothing (bare hands).

### ISSUE THREAD

**Issue by Wedge1453** [Serilum/.issue-tracker#589]
it's already possible with commands so it's supported by the game, would be nice for a undead apocalypse modpack, or a vanilla+ modpack.
and that, I guess, is in line with the concept of TVE mods, micro mods that don't change/add big features in the game.

**Comment by ricksouth** [comment]
I appreciate the new mod suggestion! I have added your idea to the list. I'm keeping track of all ideas on the Trello page and added the URL of this issue there.

In order to reduce the amount of open issues on this Github repository, I'll be closing this issue.

It definitely does not mean I am not interested and I'll post a comment here if/when the mod is released. This might take some time, as bug reports take priority. But I'll definitely be releasing more mods along the way.

Thank you very much for the suggestion!
