### ISSUE TITLE
(HuskSpawn) Config Setting To Allow Day Spawning?

### ISSUE THREAD

**Issue by JakeSublime** [Serilum/.issue-tracker#640]
## **Information**
Mod name: HuskSpawn

## **Feature description**
Config setting to allow day spawning of husks, to force the player to stay on his toes even during the day.  Would go well with the gun mod i have installed in my pack. I want ammo to be a resource to stay on top of, day spawning of husks should make that a reality. 

Also (secondarily), another config option to change how many husks can spawn around the player at any given time maybe? To make zombie survival modpacks more intense based on config settings?

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
