### ISSUE TITLE
Automate harvesting with dispenser

### ISSUE THREAD

**Issue by Knito58** [Serilum/.issue-tracker#644]
## **Information**
Mod name: Replanting Cropy

## **Feature description**
A stone hoe in a dispenser would harvest and replant the field in front.
An iron hoe 2 fields in front.
A golden hoe 3 fields.
A diamond hoe 4 fields.

Like a shear in a dispenser looking for a shearable sheep, a hoe in a dispenser would look for harvestable fields and drop everything that is more than the items used for replanting to the floor. Exactly like the sheep shearing works.
One would need some collecting mechanism like hopper minecarts to gather the crops. This would still be very vanilla but allow another way to build automated farms w/o the need for villagers.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!

**Comment by Knito58** [comment]
Thank you Sir. I just cheated and upvoted my own post with a thumbs up. If you like it that much, you could upvote it, too. :)

**Comment by ricksouth** [comment]
That won't work, but I'll help you with a rocket upvote :D
