### ISSUE TITLE
add all the other mods to TVE, like difficulty lock and configurable mob potion effects.

### ISSUE THREAD

**Issue by Wedge1453** [Serilum/.issue-tracker#648]
if it's not already planned, and doesn't cause technical difficulties.

**Comment by ricksouth** [comment]
Thanks for the interest! When I first released the TVE mod, I wrote code that combined all mods. That code doesn't work anymore, due to changes in both the mods themselves and Minecraft. There were also some other issues.

I will be attempting another TVE mod update in the near future. When that happens, I'll post another comment on here. For now I'm closing this and focusing on the other bug reports on Github. The mod is not forgotten!
