### ISSUE TITLE
Giant Spawn Drop

### ISSUE THREAD

**Issue by General-Radek** [Serilum/.issue-tracker#650]
## **Information**
Mod name: Giant Spawn

## **Feature description**
How about adding drop to giants? Let it be... some of rotten flash? From 4 to 20 pieces for example? Or just the same drop as zombies, but with more of rotten flash (what seems to be reasoned due to size :D)?

**Comment by Nevrai** [comment]
I’m all for this feature! I’m not sure what they drop currently, but if they don’t drop anything, or just drop the same drops as zombies, there’s no reason in fighting them.

Customizable drops would be fantastic, but if that’s not a possibility, giants at least dropping a lot of rotten flesh and maybe having a much higher chance of dropping rarer zombie drops—such as iron ingots, carrots, and potatoes—would be fantastic!

**Comment by James103** [comment]
> Customizable drops would be fantastic, but if that’s not a possibility, giants at least dropping a lot of rotten flesh and maybe having a much higher chance of dropping rarer zombie drops—such as iron ingots, carrots, and potatoes—would be fantastic!

This can already be done in vanilla through a data pack. The `minecraft:entities/giant` loot table can be overwritten with a loot table that drops loot as if some number of regular zombies were killed. For example, the following loot table will drop 20 zombies worth of loot whenever a giant is killed (if more or less is desired, just change the `20` in `"rolls": 20` below).
```json
{
	"pools": [
		{
			"rolls": 20,
			"entries": [
				{
					"type": "minecraft:loot_table",
					"name": "minecraft:entities/zombie"
				}
			]
		}
	]
}
```

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
