### ISSUE TITLE
Ability to trample grass blocks

### ISSUE THREAD

**Issue by louis-vinchon** [Serilum/.issue-tracker#653]
## **Information**
Mod name: [Trample Everything](https://www.curseforge.com/minecraft/mc-mods/trample-everything)

## **Feature description**
I think it would be neat, if [chanced based trampling](https://github.com/ricksouth/serilum-mc-mods/issues/652) is ever implemented, to be able to "trample" [grass blocks](https://minecraft.fandom.com/wiki/Grass_Block) into [dirt path blocks](https://minecraft.fandom.com/wiki/Dirt_Path).

No longer would I have to make up random paths, they would generate as I walk.

**Comment by James103** [comment]
By extension, there could be a way to have Trample Everything read a (CSV) file, which contains a list of block IDs and their "trampled" variant and the decimal chance (0 to 1) for the block to be trampled into its "trampled" variant. For example,
```
[original_block, trampled_block, chance]
minecraft:oxidized_copper,minecraft:weathered_copper,0.2
minecraft:weathered_copper,minecraft:exposed_copper,0.15
minecraft:exposed_copper,minecraft:copper,0.1
```
would result in copper deoxidizing as a result of players walking on top of it.

```
minecraft:stone,minecraft:coal_ore,0.01
minecraft:stone,minecraft:iron_ore,0.01
```
would result in players finding a tiny bit more coal/iron ore as a result of walking on top of their stone pathways (created from mine shafts). Note that if one block specifies multiple "trampled" variants, they are checked in the order they're listed (i.e. 1% chance for stone to turn into coal ore, but if that fails, 1% chance for stone to turn into iron ore).

**Comment by louis-vinchon** [comment]
I can already see myself leaving trails of gold blocks as I walk lol.

**Comment by James103** [comment]
Applying the proposed changes from https://github.com/ricksouth/serilum-mc-mods/issues/652#issuecomment-897703285, you would instead get the following format as an example:
```
[original_block, trampled_block, sneaking_chance, walking_chance, sprinting_chance]
minecraft:stone,minecraft:iron_block,1.0,0.0,0.0
minecraft:stone,minecraft:gold_block,0.0,1.0,0.0
minecraft:stone,minecraft:diamond_block,0.0,0.0,1.0
```
would cause all stone you move over to turn into
* Iron Blocks if you are sneaking.
* Gold Blocks if you are walking.
* Diamond Blocks if you are sprinting.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
