### ISSUE TITLE
how about a mod that makes it possible to toggle pvp combat on/off?

### ISSUE THREAD

**Issue by kuba26038** [Serilum/.issue-tracker#662]
## **Information**
Mod name: PVP toggle

## **Feature description**
i'm trying to make a server but i constantly have a problem with people being continuously killed by other players. the simplest solution would be to get on my server a mod which gives all the players the possibility to toggle their pvp via command. if pvp is set to on, the player is unable to deal any damage to other players and is unable to be damaged by other players. this option also wouldn't be toggleable in the middle of combat.

**Comment by ricksouth** [comment]
I appreciate the new mod suggestion! I have added your idea to the list. I'm keeping track of all ideas on the Trello page and added the URL of this issue there.

In order to reduce the amount of open issues on this Github repository, I'll be closing this issue.

It definitely does not mean I am not interested and I'll post a comment here if/when the mod is released. This might take some time, as bug reports take priority. But I'll definitely be releasing more mods along the way.

Thank you very much for the suggestion!
