### ISSUE TITLE
Hostiles Entering Campfire Area

### ISSUE THREAD

**Issue by djinnerator** [Serilum/.issue-tracker#667]
## **Information**
Minecraft version: 1.17.1
Forge version: 1.17.1
Environment: Singleplayer & Multiplayer

Mod name: No Hostiles Around Campfire
Mod version: 1.17

## **Description**
Steps to recreate:
1. Place campfire with default radius range (48) and modifier (0.5)
2. Wait until current hostiles die
3. Leash/lure a hostile into campfire range (distance doesn't matter)
4. Hostile does not burn/die.

## **Crash report**
N/A

## **Stuff**
I was kind of expecting new hostile entities to begin burning, but it looks like those events are only triggered when the campfire is placed. It would be cool to have have whatever triggers the initial "burning" event to get repeatedly called. I could probably implement right quick if possible. I also don't know if this is already planned on being done :D

Also don't know if this is actually considered a bug/error or should be a feature.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
