### ISSUE TITLE
HuskSpawn and StarySpawn can't be used with SpawnSkeletonHorse, SpawnZombieHorse

### ISSUE THREAD

**Issue by nxxkap** [Serilum/.issue-tracker#68]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.1.37
Environment: Singleplayer

Mod name: StraySpawn, HuskSpawn
Mod version: Both 1.15.2-1.0

## **Description**
Using SpawnHusk and SpawnStray at the same time freezes while loading the world
The same happens for Husk and SpawnSkeletonHorse, SpawnZombieHorse

## **Crash report**
If available.

**Comment by ricksouth** [comment]
Hi, thanks for submitting the issue and using the mod! This has been fixed in the latest release of both mods. The library Collective is now used to merge the two mods into one event function.

[https://www.curseforge.com/minecraft/mc-mods/stray-spawn](https://www.curseforge.com/minecraft/mc-mods/stray-spawn)
[https://www.curseforge.com/minecraft/mc-mods/husk-spawn](https://www.curseforge.com/minecraft/mc-mods/husk-spawn)

**Comment by nxxkap** [comment]
thx!!!
