### ISSUE TITLE
Compatibility with Infernal Expansion

### ISSUE THREAD

**Issue by Kutzeee** [Serilum/.issue-tracker#690]
## **Information**
Mod name: Infernal Expansion

## **Feature description**
Infernal Expansion adds a new seperate Painting item named 'Infernal Painting' and it would be cool if this type of Painting had the same functionality of regular Paintings.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Coming back to this, this is actually already a thing. By default the config disables this via the _ignorePaintingsInCycleResourceLocation_ config option. If you disable that, it will cycle like the other paintings. Thanks for the interest!
