### ISSUE TITLE
Certain group of paintings move 1 block below when you cycle the painting(compatibility issue with another mod)

### ISSUE THREAD

**Issue by Anatheras** [Serilum/.issue-tracker#70]
Minecraft version: 1.14.4
Forge version: 28.2.3
Environment: Singleplayer

Mod name: Cycle Paintings
Mod version: 1.1

###**Description**
WITH "Corail Tombstone(mod version 4.3.2)" mod installed, paintings of size (x,y) 1,1 and 1,2 move 1 block down as you change the painting and even clipping into blocks. I havent seen the other size of paintings behave this way but i might have missed some.
**Note**: without this mod it behaves as expected so there seems to be some kind of compatibility issue. I turned off every mod i had in my modpack except for corail tombstone and cycle paintings.

No crashes.

**Comment by ricksouth** [comment]
Well found! I think because the mod adds new paintings and they've also found the strange behaviour in placing paintings in a world that something changed there.

Anyways, I've fixed it in version 1.2. Everything should work as intended. Thanks for letting me know and using the mod!

[https://www.curseforge.com/minecraft/mc-mods/cycle-paintings](https://www.curseforge.com/minecraft/mc-mods/cycle-paintings)
