### ISSUE TITLE
Server freezes and then crash when a player login twice near a campfire

### ISSUE THREAD

**Issue by Giustitia** [Serilum/.issue-tracker#94]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.1.46 - 31.1.49
Environment: Singleplayer AND Multiplayer

Mod name: No Hostiles Around Campfire
Mod version: 1.15-2.1

## **Description**
Hello! So, basically server freezes and then crashes when a player logs in, disconnects and relogs near a chunk with a campfire. This started to happen after 4 days playing on the server. 7 or 8 hours before the first crash, we got raided (our town is beside a viallger town) but the raid never arrived. I don't really know if this fact is related but you know, information is never enough when bugfixing :D

Also, I tested with backups of my world from 2 days before the crash and it crashed also. What don't make sense for me is why it started crashing today, also with old world data, and it didn´t crashed 2 days ago. My guess is problem was there always, but for some reasons it didn't showed up until today.

PS: No new mods were added. We've been playing with the same mods/forge version from the beginning.
PS2: Tested both in single and multiplayer, and both in rented server and local server.

## **Crash report**
https://pastebin.com/xz6H53dx

**Comment by ricksouth** [comment]
Thanks for the detailed information! I'm going to take a look.

**Comment by ricksouth** [comment]
I couldn't replicate the issue, but I've changed some code and updated the mod to version 2.2. I'm closing the issue for now because I think it's fixed but please let me know if it isn't. Thanks for opening the issue!

[https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire](https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire)
